version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      
  backend:
    image: pe4enkaaas/foodgram_backend
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static_value:/static/
      - media_value:/app/media/

  frontend:
    image: pe4enkaaas/foodgram_frontend
    volumes:
       - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/static/
      - media_value:/media/

